version: "3.8"
services:
    app:
        build: .
        volumes:
            - .:/app
        ports:
            - 8000:8000
        image: app:index-cards-app
        container_name: index-cards-container
        command: python manage.py runserver 0.0.0.0:8000
