# Generated by Django 4.1.5 on 2023-01-24 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessioncard',
            name='user_answer',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='practisesession',
            name='session_start',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
