# Generated by Django 4.1.5 on 2023-01-24 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_sessioncard_user_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='topic_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
